metadata.musicvideos.theaudiodb.com/addon.xml
metadata.musicvideos.theaudiodb.com/changelog.txt
metadata.musicvideos.theaudiodb.com/tadb.xml

Escape apostrophes in filenames with a backslash like so, (\'), so that they can be scraped by theaudiodb music video scraper.
See [this issue in the forum](http://forum.kodi.tv/showthread.php?pid=1809327#pid1809327)
>I used this addon recently for the first time, and it had trouble finding matches for artists/titles that contained an apostrophe ( ' ).
I found that this could be fixed by replacing the apostrophe ( ' ) with backslash+apostrophe ( \' ) when adding manually the files to the library from within XMBC.
e.g.: The Weather Girls - It's Raining Men ---> The Weather Girls - It\'s Raining Men
Actually, the search field of TheAudioDB.com is doing this substitution. Just try searching for something and then in the results page see the text chain after "Search Results for...".
This …

fix(scraper-tadb): escape apostrophes in names

---

metadata.tvdb.com/addon.xml
metadata.tvdb.com/changelog.txt
metadata.tvdb.com/tvdb.xml

Runtime could be zero, as it could not be found, when the rating/vote match hits.
In that case it's overwriting buffer 1 before the runtime has a chance of getting extracted.
```<RegExp input="$$11">``` seems to fall back to buffer 1 as it's not set, so it's overwritten
So I moved the processing of the runtime before that code for now.

Fixed runtime beeing zero in some cases

---

metadata.universal/resources/language/English/strings.po
metadata.universal/resources/settings.xml
metadata.universal/universal.xml

In PR 10, i introduced a problem where TMDB and IMDB search services can be both selected. The fix to it is included here.
Before this PR can be merged:
1) two subsettings for Rotten Tomatoes as the rating source were not being shown. I fixed them too. I checked to make sure the function did have the capability to handle the choices. Is there a chance that they were hidden on purpose?
2) wouldn't it look better if the Search category, would contain a "labelenum" for selecting the service provider?

Cleanup of the Settings dialog for metadata.universal

---

metadata.common.musicbrainz.org/addon.xml
metadata.common.musicbrainz.org/musicbrainz.xml

If you open http://musicbrainz.org/ws/2/release-group?artist=298909e4-ebcb-47b8-95e9-cc53b087fc65&limit=100&type=album for example.
The ```type="Album"``` is either before or after the ```id="XXXXXXXXXX"``` this PR takes this into account and will also grab the ones where ```type="Album"``` is behind the id-tag.
If you don't see it on the link, please refresh a few times.

Improved regex to match when type="Album" is not at the same position

---

metadata.tvdb.com/addon.xml
metadata.tvdb.com/changelog.txt
metadata.tvdb.com/resources/language/English/strings.po
metadata.tvdb.com/resources/settings.xml
metadata.tvdb.com/tvdb.xml

This is an update of the TVDB scraper to use their 2.0 API.
It includes all the additional features added in my previous XSLT version, as detailed in my [forum post](https://forum.kodi.tv/showthread.php?tid=259457) . (Except for the Trakt ratings, they're no longer possible for unrelated reasons.)
It also includes a language fallback option that will perform the title search in a secondary language, and also fetch titles and plots in that language if they're not available in the primary language.
I've added some backwards compatibility code so existing episodeguide URLs will continue to work (essentially it just takes the ID from the old URL and runs the function again with the new URL), however this won't help if/when the old URLs return a 404 error (or similar) since Kodi just won't run …

[metadata.tvdb.com] updated to v2.0.0

---

metadata.tvdb.com/addon.xml
metadata.tvdb.com/changelog.txt
metadata.tvdb.com/tvdb.xml

So it turns out that backwards-compatibility code didn't work because I missed out the www on the URL it checked against.
I am so sorry and embarrassed.  I swear I tested it.  I don't know what happened.
- [x ] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [ x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scrapers/blob/master/CONTRIBUTING.md) document
- [ x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

[metadata.tvdb.com] updated to v2.0.1

---

metadata.tvdb.com/addon.xml
metadata.tvdb.com/changelog.txt
metadata.tvdb.com/resources/settings.xml
metadata.tvdb.com/tvdb.xml

Fix for: [IMDb ratings not working](https://forum.kodi.tv/showthread.php?tid=323230&pid=2663337#pid2663337).
Also added the www to the artwork URLs, per @thezoggy (Thanks).
I've also renamed and reset the fallback language option so that it defaults to true.  This should provide an experience closer to the old scraper for people not using English, without them having to change the settings.
The scraper is smart enough to not duplicate effort if the fallback language is the same as the default language, so there should be no effect on English language users.
The only people negatively affected would be those who turned it on, decided they didn't like it and then turned it back off.  There's bound to be one.

[metadata.tvdb.com] updated to v2.0.3

---

metadata.tvdb.com/addon.xml
metadata.tvdb.com/changelog.txt
metadata.tvdb.com/tvdb.xml

Fixes using IMDb ratings blocking Actor scraping.
The call to GetIMDBRatingById was simply clearing the buffers before GetActors could use the Authorization token.  Swapping the order around fixed it easily enough.
I may also have inadvertently fixed the issue with IMDb ratings not showing when using German language.
At some point  I had put $INFO[language] (and some random buffer) into a comment on the output of GetDetails for debugging purposes, and _somehow_ this was causing the IMDb page to have German numbering style... _maybe_? 
I do not understand the connection, but I tested it enough to know it works without it, but not with it.  So I removed it.

[metadata.tvdb.com] updated to v2.0.4

---

metadata.common.imdb.com/addon.xml
metadata.common.imdb.com/changelog.txt
metadata.common.imdb.com/imdb.xml
metadata.common.omdbapi.com/addon.xml
metadata.common.omdbapi.com/changelog.txt
metadata.common.omdbapi.com/omdbapi.xml
metadata.common.themoviedb.org/addon.xml
metadata.common.themoviedb.org/tmdb.xml

This is an update and streamlining of the new code for ratings in the common libraries.  I didn't see any other scrapers using the current code, so I felt it safe to change it.
Instead of having two near-identical (pairs of) functions differing only by the inclusion of the default="true", there's now just one, which you either chain with just the id e.g.:
`<chain function="GetIMDBRatingsById">tt2294449</chain>` for non-default rating.
Or with the addition of "|default" for the default ratings, e.g.:
`<chain function="GetMetaCriticRatingsById">tt2294449|default</chain>`
As you'll see in the next PR, this can all be handled in a single RegExp (per rating) in the Universal scraper, so it results in no major code increase. The tvdb scraper is slightly more complicated, but not by much.
I also …

Ratings code updates

---

metadata.themoviedb.org/addon.xml
metadata.themoviedb.org/changelog.txt
metadata.themoviedb.org/tmdb.xml
metadata.tvdb.com/addon.xml
metadata.tvdb.com/changelog.txt
metadata.tvdb.com/tvdb.xml
metadata.universal/addon.xml
metadata.universal/changelog.txt
metadata.universal/universal.xml

In my focus on the ratings code, I overlooked that a default="true" also needs to be on the uniqueids.

Uniqueidfixes

---

metadata.themoviedb.org/addon.xml
metadata.themoviedb.org/changelog.txt
metadata.themoviedb.org/tmdb.xml

Makes themoviedb scraper save the imdb uniqueid as default (when available), as per [the discussion](https://github.com/xbmc/repo-scrapers/commit/9dbe28fa7dbe23e6c0288d93b2fbcb620c0adc82#comments).

[metadata.themoviedb.org] updated to v5.0.3

---

metadata.common.imdb.com/addon.xml
metadata.common.imdb.com/changelog.txt
metadata.common.imdb.com/imdb.xml

Change to fetch TV-* certifications for movies that only have them, instead of having these titles stored as _Not Rated_.
Movies like [The Ridiculous 6 (2015)](http://www.imdb.com/title/tt2479478/reference), [Special Correspondents (2016)](http://www.imdb.com/title/tt4181052/reference), [War Machine (2017)](http://www.imdb.com/title/tt4758646/reference), [Sandy Wexler (2017)](http://www.imdb.com/title/tt5893332/reference), or [Okja (2017)](http://www.imdb.com/title/tt3967856/reference), using the existing logic of matching against `(P?G|PG-13|R|NC-17)`, don't get a certification stored for them.
I made the TV-* a separate pattern so that movies like [Mad Max (1979)](http://www.imdb.com/title/tt0079501/reference), which have both TV-* and MPAA certifications, will prioritize the MPAA one. …

[metadata.common.imdb.com] v3.0.2 - Use TV certification in the absence of MPAA ones

---

metadata.common.fanart.tv/addon.xml
metadata.common.fanart.tv/fanarttv.xml

To avoid foreign-language image downloads for media types that commonly
contain localized text, language filters are added to the following
sections:
- GetFanartTvMoviebannerByIdChain
- GetFanartTvMovieClearartByIdChain
- GetFanartTvMovieClearlogoByIdChain
- GetFanartTvMovieDiscartByIdChain
- GetFanartTvMovieLandscapeByIdChain
Fixes https://trac.kodi.tv/ticket/17854
This is the first time I've worked on these XML scrapers so a close review would be appreciated.

[metadata.common.fanart.tv] Add language filters to additional media types

---

metadata.universal/addon.xml
metadata.universal/changelog.txt
metadata.universal/universal.xml

To avoid foreign-language image downloads for media types that commonly
contain localized text, language filters are added to the following
sections:
- GetFanartTvMoviebannerByIdChain
- GetFanartTvMovieClearartByIdChain
- GetFanartTvMovieClearlogoByIdChain
- GetFanartTvMovieDiscartByIdChain
- GetFanartTvMovieLandscapeByIdChain
I did not create a new setting to control the language of each media type individually, but re-used the Poster language, I think this is always what users expect in any case.
This is the first time I've worked on these XML scrapers so a close review would be appreciated.
Depends on https://github.com/xbmc/repo-scrapers/pull/73
Fixes https://trac.kodi.tv/ticket/17854

[metadata.universal] Add language filters to additional fanart.tv media types

---

metadata.tvdb.com/addon.xml
metadata.tvdb.com/changelog.txt
metadata.tvdb.com/tvdb.xml

The tvdb removed the spaces from the JSON output of it's api.
I've replaced the spaces in the regexes with \s* for safety.
Krypton version.

[metadata.tvdb.com] updated to version 3.0.2

---

metadata.tvdb.com/addon.xml
metadata.tvdb.com/changelog.txt
metadata.tvdb.com/tvdb.xml

Fix for missing artwork.  A new LanguageId field was added to the api... for some reason I can't fathom.
Also  includes a fix for directors turning up as guest stars in episodes.
Gotham version.

[metadata.tvdb.com] updated to v2.0.9

---

metadata.tvdb.com/addon.xml
metadata.tvdb.com/changelog.txt
metadata.tvdb.com/tvdb.xml

Quick and dirty(ish) fix for the new episode list changes.
It should be possible to update to reduce the number of api calls that get made, since all the episode info is now included, so we don't have to call for each episode individually any more, but that will take a bit more work to implement.

[metadata.tvdb.com] updated to v3.0.7

---

metadata.tvdb.com/addon.xml
metadata.tvdb.com/changelog.txt
metadata.tvdb.com/tvdb.xml

Fix (hopefully) for tvdb issues with apostrophes.  
I think some double encoding must be going on, because the titles and such are fixchar'd in the scraper once already.
Krypton version.

[metadata.tvdb.com] updated to v3.0.8

---

metadata.tvdb.com/addon.xml
metadata.tvdb.com/changelog.txt
metadata.tvdb.com/tvdb.xml

Placed the fixchar too early in the search results, which, it turns out, could break the xml before being passed to the xslt.  
(Probably due to ampersands in the search results.)

[metadata.tvdb.com] updated to v3.0.9

---

metadata.tvdb.com/addon.xml
metadata.tvdb.com/changelog.txt
metadata.tvdb.com/tvdb.xml

(Sort-of) Fix for the missing firstAired field from tvdb causing mismatches.
It captures the year from the title, if there is one, and uses that as fallback for the firstAired field in the search results.

[metadata.tvdb.com] updated to v3.0.10

---

metadata.tvdb.com/addon.xml
metadata.tvdb.com/changelog.txt
metadata.tvdb.com/tvdb.xml

theTVDb API has started filling in empty DVD and Absolute season and episode numbers with zeros, rather than leaving them as NULL, which prevents the scraper from using fallbacks.
While fixing that, I noticed a few other mistakes in the handling of DVD and Absolute orders, chief among them being that using IMDB ratings would clear buffers that need to remain while adding multiple episodes, so I had to include those functions in the scraper to add the `clearbuffers="no"` to ParseIMDBRatings .  I could have just added it to the common library, but was fearful of unintended consequences for other scrapers.

[metadata.tvdb.com] updated to v3.0.12

---

metadata.tvdb.com/addon.xml
metadata.tvdb.com/changelog.txt
metadata.tvdb.com/tvdb.xml

This adds support for using the current slug-based URLs from thetvdb in nfo files.

[metadata.tvdb.com] updated to v3.0.13

---

metadata.tvshows.themoviedb.org/addon.xml
metadata.tvshows.themoviedb.org/changelog.txt
metadata.tvshows.themoviedb.org/tmdb.xml

This update includes the changes as discussed in the forums to reduce the number of API calls.
It also includes a 15 minute cache persistence, which may or may not help, but can't hurt.
It also, more significantly, includes Episode Group and Named Season support.
The Episode Group support works via nfo files.  The user needs to include the Episode Group URL in the tvshow.nfo, and the scraper will then save the Episode Group id along with the show id and use it when building the episode list.  
There are a few caveats to this, the Groups are always numbered in order, starting at 1, regardless of how they are _named_ on the site.  This can differ from thetvdb where the first season might be _numbered_ "2010" and you would have to number the files s2010e01, etc.  With the Episode Groups, …

[metadata.tvshows.themoviedb.org] updated to v3.1.0

---

metadata.themoviedb.org/addon.xml
metadata.themoviedb.org/resources/settings.xml

The language code "zh-cn" for Chinese is not working with TMDB. Need to be corrected.
See https://github.com/xbmc/xbmc/issues/15852

[metadata.themoviedb.org] v5.1.6 Fix language code for Chinese

---

metadata.themoviedb.org/addon.xml
metadata.themoviedb.org/changelog.txt
metadata.themoviedb.org/tmdb.xml

[metadata.themoviedb.org] updated to v4.1.6

---

metadata.universal/addon.xml
metadata.universal/changelog.txt
metadata.universal/universal.xml

Fixed TMDB search failure.
With v5.3.3, I was getting `scraper: GetSearchResults returned <results></results>`.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). …

[metadata.universal] v5.3.4

---

metadata.tvmaze/addon.xml
metadata.tvmaze/libs/actions.py
metadata.tvmaze/libs/cache.py
metadata.tvmaze/libs/data_utils.py
metadata.tvmaze/libs/tvmaze.py

- **General**
- Add-on name: TVmaze
- Add-on ID: metadata.tvmaze
- Version number: 1.0.1
- Kodi/repository version: leia
- **Code location**
- URL: https://github.com/romanvm/kodi.tvmaze
TVmaze is a free user driven TV database curated by TV lovers all over the world. You can track your favorite shows from anywhere.
We provide an API that can be used by anyone or service like Kodi to retrieve TV Metadata, show/episode/cast images, and much more.
1.0.0:
- Fixed a bug with empty ratings.
- Added a workaround for a Kodi bug when episoude guide URL from NFO is passed to a scraper.
- Artwork is now sorted by main property.

[metadata.tvmaze] 1.0.1

---

metadata.tvshows.themoviedb.org/addon.xml
metadata.tvshows.themoviedb.org/changelog.txt
metadata.tvshows.themoviedb.org/tmdb.xml

Whole bunch of updates/fixes.  
Starting at the top:
1. Added the year to the search query.
2. Tidied GetSearchResults, and added results based on the "name" field when it differs from "original_name" (fixes https://forum.kodi.tv/showthread.php?tid=200504&pid=2927244#pid2927244 where other series' original_names are a closer match than the one intended).
3. Removed the unnecessary GetTVShowExtIDs function.  External ids are appended to the main details anyway.  They can added directly without downloading an extra file.
4. Same with GetIMDbTVShowRating.  The imdb id is already there, so the actual rating function can be called directly.
5. Same with ParseTVShowContentRating.  The content rating is already appended.
6. Changed the GetCast function to use the season files (with credits …

[metadata.tvshows.themoviedb.org] updated to v3.5.0

---

metadata.common.fanart.tv/addon.xml
metadata.common.fanart.tv/fanarttv.xml

[metadata.common.fanart.tv] updated to v3.6.3

---

metadata.tvmaze/addon.xml
metadata.tvmaze/libs/__init__.py
metadata.tvmaze/libs/actions.py
metadata.tvmaze/libs/cache.py
metadata.tvmaze/libs/data_utils.py
metadata.tvmaze/libs/debugger.py
metadata.tvmaze/libs/tvmaze.py
metadata.tvmaze/libs/utils.py
metadata.tvmaze/main.py

- **General**
- Add-on name: TVmaze
- Add-on ID: metadata.tvmaze
- Version number: 1.0.2+matrix.1
- Kodi/repository version: matrix
- **Code location**
- URL: https://github.com/romanvm/kodi.tvmaze
TVmaze is a free user driven TV database curated by TV lovers all over the world. You can track your favorite shows from anywhere.
We provide an API that can be used by anyone or service like Kodi to retrieve TV Metadata, show/episode/cast images, and much more.
1.0.2:
- Fixed a workaround for Kodi episodeguide URL bug.

[metadata.tvmaze@matrix] 1.0.2+matrix.1
