xbmc/repo-scrapers

metadata.tvdb.com/addon.xml, metadata.tvdb.com/changelog.txt, metadata.tvdb.com/tvdb.xml
Needed for the upcoming season artwork refresh changes in https://github.com/xbmc/xbmc/pull/6902. There's no change in behavior with this change.
@olympia for review please.
=> [metadata.tvdb.com] updated to 1.7.2

metadata.universal/resources/language/English/strings.po, metadata.universal/resources/settings.xml, metadata.universal/universal.xml
Part of an effort to bring in search lang, caching (where missing), tmdb urls in NFO files and standardizing the settings appearance.
=> Preferred search language for TMDB

metadata.tvdb.com/addon.xml, metadata.tvdb.com/changelog.txt, metadata.tvdb.com/tvdb.xml
In preparation for https://github.com/xbmc/xbmc/pull/9212
@olympia
=> Parse tvshow runtime

metadata.filmweb.pl/addon.xml, metadata.filmweb.pl/changelog.txt, metadata.filmweb.pl/filmweb.xml, metadata.filmweb.pl/resources/language/English/strings.xml, metadata.filmweb.pl/resources/language/Polish/strings.xml, metadata.filmweb.pl/resources/settings.xml
=> [metadata.filmweb.pl] 2.3.0

metadata.filmaffinity.com/addon.xml, metadata.filmaffinity.com/changelog.txt, metadata.filmaffinity.com/filmaffinity.xml
=> [metadata.filmaffinity.com] v1.7.2 Fix year

metadata.filmaffinity.com/addon.xml, metadata.filmaffinity.com/changelog.txt, metadata.filmaffinity.com/filmaffinity.xml
=> [metadata.filmaffinity.com] v1.7.3 Improve filmaffinity changed fields

metadata.filmaffinity.com/addon.xml, metadata.filmaffinity.com/changelog.txt, metadata.filmaffinity.com/filmaffinity.xml
=> metadata.filmaffinity.com 1.7.6 review trailer search

metadata.atmovies.com.tw/AtMovies.xml, metadata.atmovies.com.tw/addon.xml, metadata.atmovies.com.tw/changelog.txt
Fixed for new www.atmovies.com.tw site layout and added new fucntion for getting url from NFO files
=> [metadata.atmovies.com.tw] 1.6.5

metadata.tvdb.com/addon.xml, metadata.tvdb.com/changelog.txt, metadata.tvdb.com/tvdb.xml
Fixes for:
[Special episode placement not working](https://forum.kodi.tv/showthread.php?tid=323354).
[Generated thumbnails being blocked](https://forum.kodi.tv/showthread.php?tid=323230&pid=2662458#pid2662458).
I've also added the fallback language to the artwork downloading.
=> [metadata.tvdb.com] updated to v2.0.2

metadata.tvdb.com/addon.xml, metadata.tvdb.com/changelog.txt, metadata.tvdb.com/tvdb.xml
Apparently Kodi doesn't clear headers between requests during a scrape, so the (capitalised) Accept-Language from the TVDB scraper was interfering with the (all lower-case) accept-language from the IMDb scraper.
Avoided by simply making the TVDB scraper use all lower-case too.
You can still verify the larger issue by turning on libcURL component logging and scraping a show with IMDb ratings, then noting that the Authorization header from the TVDB URLs is also being sent to IMDb.
- Kodi …
=> [metadata.tvdb.com] updated to v2.0.5

metadata.filmaffinity.com/addon.xml, metadata.filmaffinity.com/changelog.txt, metadata.filmaffinity.com/filmaffinity.xml, metadata.filmaffinity.com/resources/settings.xml
=> [metadata.filmafinity.com] 1.8.1 - Update poster retrieval

metadata.filmaffinity.com/addon.xml, metadata.filmaffinity.com/changelog.txt, metadata.filmaffinity.com/filmaffinity.xml
=> [metadata.filmaffinity.com] 1.9.2 Update TMDB API

metadata.tvshows.themoviedb.org/addon.xml, metadata.tvshows.themoviedb.org/changelog.txt, metadata.tvshows.themoviedb.org/tmdb.xml
fixes https://trac.kodi.tv/ticket/17348
backports #75
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously …
=> [metadata.tvshows.themoviedb.org] 1.3.11

metadata.tvshows.themoviedb.org/addon.xml, metadata.tvshows.themoviedb.org/changelog.txt, metadata.tvshows.themoviedb.org/tmdb.xml
fixes https://trac.kodi.tv/ticket/17348
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your …
=> [metadata.tvshows.themoviedb.org] 3.0.3

metadata.tvshows.themoviedb.org/addon.xml, metadata.tvshows.themoviedb.org/changelog.txt, metadata.tvshows.themoviedb.org/tmdb.xml
fixes https://trac.kodi.tv/ticket/17348
backports #75
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously …
=> [metadata.tvshows.themoviedb.org] 2.0.4

metadata.filmaffinity.com/addon.xml, metadata.filmaffinity.com/changelog.txt, metadata.filmaffinity.com/filmaffinity.xml
=> [metadata.filmafinity.com] 1.9.3 Update TMDB Configuration

metadata.tvdb.com/addon.xml, metadata.tvdb.com/changelog.txt, metadata.tvdb.com/tvdb.xml
The tvdb removed the spaces from the JSON output of it's api.
I've replaced the spaces in the regexes with \s* for safety.
Gotham version.
=> [metadata.tvdb.com] updated to v2.0.6

metadata.tvdb.com/addon.xml, metadata.tvdb.com/changelog.txt, metadata.tvdb.com/tvdb.xml
=> [metadata.tvdb.com] updated to v3.0.6

metadata.tvdb.com/addon.xml, metadata.tvdb.com/changelog.txt, metadata.tvdb.com/tvdb.xml
=> [metadata.tvdb.com] updated to v2.0.11

metadata.tvdb.com/addon.xml, metadata.tvdb.com/changelog.txt, metadata.tvdb.com/tvdb.xml
=> [metadata.tvdb.com] updated to v2.0.12

metadata.tvdb.com/addon.xml, metadata.tvdb.com/changelog.txt, metadata.tvdb.com/tvdb.xml
=> [metadata.tvdb.com] updated to v2.0.13

metadata.tvdb.com/addon.xml, metadata.tvdb.com/changelog.txt, metadata.tvdb.com/tvdb.xml
=> [metadata.tvdb.com] updated to v2.0.14

metadata.filmaffinity.com/addon.xml, metadata.filmaffinity.com/changelog.txt, metadata.filmaffinity.com/filmaffinity.xml
Change IMDB Api key
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before …
=> [metadata.filmafinity.com] 1.9.4

metadata.tvdb.com/addon.xml, metadata.tvdb.com/changelog.txt, metadata.tvdb.com/tvdb.xml
=> [metadata.tvdb.com] updated to v2.0.16

metadata.tvdb.com/addon.xml, metadata.tvdb.com/changelog.txt, metadata.tvdb.com/tvdb.xml
=> [metadata.tvdb.com] updated to v2.0.17

metadata.common.musicbrainz.org/addon.xml, metadata.common.musicbrainz.org/musicbrainz.xml
Set the max rating for Music Brainz to 5 so Kodi can correctly convert to a 1-10 scale
Fixes incorrect album ratings when using Music Brainz as the album rating provider in Universal Album Scraper
Yes, tested on many albums and compared with results on Music Brainz site
=> [metadata.common.musicbrainz.org] v2.2.1

metadata.tvdb.com/addon.xml, metadata.tvdb.com/changelog.txt, metadata.tvdb.com/tvdb.xml
Done as advised in https://forum.kodi.tv/showthread.php?tid=337445&pid=2791405#pid2791405
@ScudLee
=> [metadata.tvdb.com] 2.0.18

metadata.tvdb.com/addon.xml, metadata.tvdb.com/changelog.txt, metadata.tvdb.com/tvdb.xml
Same as in https://github.com/xbmc/repo-scrapers/pull/107 but for krypton and onwards
=> [metadata.tvdb.com] 3.0.14

metadata.tvshows.themoviedb.org/addon.xml, metadata.tvshows.themoviedb.org/tmdb.xml
It probably would help if I bumped the version number in addon.xml as well...
Still, I spotted a slight bug in episode plot handling, so at least I could fix that too before anyone got hit by it.
=> [metadata.tvshows.themoviedb.org] (really) updated to v3.1.0

metadata.artists.universal/addon.xml, metadata.artists.universal/artistuniversal.xml, metadata.artists.universal/changelog.txt
=> [metadata.artists.universal] updated to v4.3.2

metadata.tvdb.com/addon.xml, metadata.tvdb.com/changelog.txt, metadata.tvdb.com/tvdb.xml
Fix crash for empty artwork
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding …
=> [metadata.tvdb.com] v3.1.16

metadata.tvdb.com/addon.xml, metadata.tvdb.com/changelog.txt, metadata.tvdb.com/tvdb.xml
Backport of https://github.com/xbmc/repo-scrapers/pull/127
=> [metadata.tvdb.com] v2.0.19

metadata.tvshows.themoviedb.org/addon.xml, metadata.tvshows.themoviedb.org/changelog.txt, metadata.tvshows.themoviedb.org/tmdb.xml
=> [metadata.tvshows.themoviedb.org] updated v3.1.3

metadata.tvshows.themoviedb.org/addon.xml, metadata.tvshows.themoviedb.org/changelog.txt, metadata.tvshows.themoviedb.org/tmdb.xml
This is the same change @olympia did for the Kodi v18 version (3.1.3). Not saying that I understand what has been changed, but it works for me a user confirms that it works as well. Please see:
https://github.com/xbmc/xbmc/issues/16540
- This add-on repository has automated code guideline check which could help you …
=> [metadata.tvshows.themoviedb.org] updated v2.0.9

metadata.common.themoviedb.org/addon.xml, metadata.common.themoviedb.org/tmdb.xml
=> [metadata.common.themoviedb.org] updated to v3.1.10

metadata.themoviedb.org/addon.xml, metadata.themoviedb.org/changelog.txt, metadata.themoviedb.org/tmdb.xml
=> [metadata.themoviedb.org] updated to v5.1.9

metadata.universal/addon.xml, metadata.universal/changelog.txt, metadata.universal/universal.xml
=> [metadata.universal] updated to v5.3.2

metadata.universal/addon.xml, metadata.universal/changelog.txt, metadata.universal/universal.xml
=> [metadata.universal] updated to v4.1.13

metadata.universal/addon.xml, metadata.universal/changelog.txt, metadata.universal/universal.xml
=> [metadata.universal] updated to v2.9.10

metadata.universal/addon.xml, metadata.universal/universal.xml
=> [metadata.universal updated to v5.3.3

metadata.universal/addon.xml, metadata.universal/changelog.txt, metadata.universal/universal.xml
=> [metadata.universal] updated to v4.1.14

metadata.universal/addon.xml, metadata.universal/changelog.txt, metadata.universal/universal.xml
=> [metadata.universal] updated to v2.9.11

metadata.common.theaudiodb.com/addon.xml, metadata.common.theaudiodb.com/tadb.xml
=> [metadata.common.theaudiodb.com] updated to v2.0.3

metadata.common.fanart.tv/addon.xml, metadata.common.fanart.tv/fanarttv.xml
=> [metadata.common.fanart.tv] updated to v3.6.2

metadata.common.allmusic.com/addon.xml, metadata.common.allmusic.com/allmusic.xml
=> [metadata.common.allmusic.com] updated to v3.2.1

metadata.tvshows.themoviedb.org/addon.xml, metadata.tvshows.themoviedb.org/tmdb.xml
Also parse https links for tvdb urls.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your …
=> [metadata.tvshows.themoviedb.org] 3.1.4

metadata.filmaffinity.com/addon.xml, metadata.filmaffinity.com/changelog.txt, metadata.filmaffinity.com/filmaffinity.xml
Update scrapper to fix issues with posters
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your …
=> [metadata.filmaffinity.com] v1.9.5

metadata.tvdb.com/addon.xml, metadata.tvdb.com/changelog.txt, metadata.tvdb.com/tvdb.xml
=> [metadata.tvdb.com] updated to v3.2.0

metadata.themoviedb.org/addon.xml, metadata.themoviedb.org/changelog.txt, metadata.themoviedb.org/tmdb.xml
=> [metadata.themoviedb.org] updated to v5.1.10

metadata.universal/addon.xml, metadata.universal/changelog.txt, metadata.universal/universal.xml
=> [metadata.universal] updated to v4.1.15

metadata.universal/addon.xml, metadata.universal/changelog.txt, metadata.universal/universal.xml
=> [metadata.universal] updated to v5.3.5

metadata.tvdb.com/addon.xml, metadata.tvdb.com/changelog.txt, metadata.tvdb.com/tvdb.xml
=> [metadata.tvdb.com] updated to v3.2.1

metadata.tvdb.com/addon.xml, metadata.tvdb.com/changelog.txt, metadata.tvdb.com/tvdb.xml
=> [metadata.tvdb.com] updated to 2.1.1

metadata.themoviedb.org/addon.xml, metadata.themoviedb.org/changelog.txt, metadata.themoviedb.org/tmdb.xml
=> [metadata.themoviedb.org] updated to v4.1.7

metadata.universal/addon.xml, metadata.universal/changelog.txt, metadata.universal/resources/language/English/strings.po, metadata.universal/universal.xml
=> [metadata.universal] updated to v2.9.12

metadata.tvshows.themoviedb.org/addon.xml, metadata.tvshows.themoviedb.org/changelog.txt, metadata.tvshows.themoviedb.org/resources/language/resource.language.en_gb/strings.po, metadata.tvshows.themoviedb.org/resources/settings.xml, metadata.tvshows.themoviedb.org/tmdb.xml
=> [metadata.tvshows.themoviedb.org] updated to v3.3.0

metadata.tvshows.themoviedb.org/addon.xml, metadata.tvshows.themoviedb.org/changelog.txt, metadata.tvshows.themoviedb.org/resources/language/resource.language.en_gb/strings.po, metadata.tvshows.themoviedb.org/resources/settings.xml, metadata.tvshows.themoviedb.org/tmdb.xml
=> [metadata.tvshows.themoviedb.org] updated to v3.4.0

metadata.tvdb.com/addon.xml, metadata.tvdb.com/changelog.txt, metadata.tvdb.com/tvdb.xml
=> [metadata.tvdb.com] updated to v3.2.2

metadata.tvdb.com/addon.xml, metadata.tvdb.com/changelog.txt, metadata.tvdb.com/tvdb.xml
=> [metadata.tvdb.com] updated to v3.2.3

README.md
=> Remove Trac from other useful links section

metadata.tvdb.com/addon.xml, metadata.tvdb.com/changelog.txt, metadata.tvdb.com/tvdb.xml
=> [metadata.tvdb.com] updated to v3.2.4

metadata.tvdb.com/addon.xml, metadata.tvdb.com/changelog.txt, metadata.tvdb.com/tvdb.xml
Backport of Krypton updates for v3.2.2, 3.2.3 & 3.2.4
=> [metadata.tvdb.com] Update to v2.1.4

metadata.tvshows.themoviedb.org/addon.xml, metadata.tvshows.themoviedb.org/changelog.txt, metadata.tvshows.themoviedb.org/tmdb.xml
Square / Round brackets in plot fix
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python …
=> [metadata.tvshows.themoviedb.org] Updated to v3.4.2

metadata.tvshows.themoviedb.org/addon.xml, metadata.tvshows.themoviedb.org/changelog.txt, metadata.tvshows.themoviedb.org/resources/language/resource.language.en_gb/strings.po, metadata.tvshows.themoviedb.org/resources/settings.xml, metadata.tvshows.themoviedb.org/tmdb.xml
=> [metadata.tvshows.themoviedb.org] updated to v3.5.1

metadata.common.imdb.com/addon.xml, metadata.common.imdb.com/changelog.txt, metadata.common.imdb.com/imdb.xml
=> [metadata.common.imdb.com] updated to v3.1.5

metadata.universal/addon.xml, metadata.universal/changelog.txt, metadata.universal/universal.xml
=> [metadata.universal updated to 2.9.13

metadata.universal/addon.xml, metadata.universal/changelog.txt, metadata.universal/universal.xml
=> [metadata.universal updated to v4.1.16

metadata.universal/addon.xml, metadata.universal/changelog.txt, metadata.universal/universal.xml
=> [metadata.universal updated to v5.3.6

metadata.themoviedb.org/addon.xml, metadata.themoviedb.org/changelog.txt, metadata.themoviedb.org/resources/settings.xml
added Belarusian language
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding …
=> [metadata.themoviedb.org] updated to v4.1.8

metadata.themoviedb.org/addon.xml, metadata.themoviedb.org/changelog.txt, metadata.themoviedb.org/resources/settings.xml
Added Belarusian language option
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python …
=> [metadata.themoviedb.org] updated to v5.1.11

metadata.common.themoviedb.org/addon.xml, metadata.common.themoviedb.org/tmdb.xml
=> [metadata.common.themoviedb.org] updated to v3.1.11

metadata.common.themoviedb.org/addon.xml, metadata.common.themoviedb.org/tmdb.xml
=> [metadata.common.themoviedb.org] update to v3.2.0

metadata.themoviedb.org/addon.xml, metadata.themoviedb.org/changelog.txt, metadata.themoviedb.org/resources/language/resource.language.en_gb/strings.po, metadata.themoviedb.org/resources/settings.xml, metadata.themoviedb.org/tmdb.xml
=> [metadata.themoviedb.org] updated to v5.2.0

metadata.universal/addon.xml, metadata.universal/changelog.txt, metadata.universal/resources/language/resource.language.en_gb/strings.po, metadata.universal/resources/settings.xml, metadata.universal/universal.xml
=> [metadata.universal updated to v5.4.0

metadata.tvdb.com/addon.xml, metadata.tvdb.com/changelog.txt, metadata.tvdb.com/tvdb.xml
Fix scraping of Plot and title due to changes in API
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously …
=> [metadata.tvdb.com] updated to v2.1.5

metadata.tvdb.com/addon.xml, metadata.tvdb.com/changelog.txt, metadata.tvdb.com/tvdb.xml
Backport of v3.2.6 and v3.2.7 by olympia
Fixes for missing episode titles and plots
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own …
=> [metadata.tvdb.com] updated to v2.1.7
